server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://quipu-user.mysql.database.azure.com:3306/user_db?useSSL=true"
    username: quipu_user
    password: User12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
  instances:
    myCircuitBreaker:
      baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
